import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Platzi</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1 className="text-3xl font-bold underline">
                    Hello World on NextJS!
                </h1>
            </main>

            <footer>

            </footer>
        </div>
    )
}

export default Home
